# .github/workflows/main.yml

name: Dockerized Python CI/CD

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-test-docker:
    runs-on: ubuntu-latest

    environment:
      name: default

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker images
      run: docker-compose build

    - name: Run Docker Compose services and tests
      run: docker-compose up --abort-on-container-exit --exit-code-from app
      env:
        POSTGRES_DB: ${{ vars.TEST_DB_NAME }}
        POSTGRES_USER: ${{ vars.TEST_DB_USERNAME }}
        POSTGRES_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}

    - name: Clean up Docker Compose services
      if: always()
      run: docker-compose down -v